version: '3.1'

networks:
  betta:
    driver: bridge

services:
  database:
    image: postgres
    restart: always
    networks:
      - betta
  
    environment: 
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
  
    ports:
      - "5432:5432"
  
    volumes:
      - ./pg_data/:/var/lib/postgresql/dat